theme: jekyll-theme-minimal
title: [Dardeery's portfolio]
description: [This is my porfolio covering my work in analytics and data visualization]
logo: [Location of the logo]
show_downloads: ["true"]
